# Generated by Django 3.2.3 on 2021-05-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorvete',
            options={'ordering': ['-id'], 'verbose_name': 'Sorvete', 'verbose_name_plural': 'Sorvetes'},
        ),
    ]
