# Generated by Django 3.2.3 on 2021-05-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sorvete_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('nota', models.DecimalField(decimal_places=0, max_digits=2)),
                ('comentario', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AlterModelOptions(
            name='sorvete',
            options={'verbose_name': 'Sorvete', 'verbose_name_plural': 'Sorvetes'},
        ),
    ]
