# Generated by Django 3.2.3 on 2021-05-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210525_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='sorvete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sorvete'),
        ),
    ]
