# Generated by Django 3.2.3 on 2021-05-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_avaliacao_sorvete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='sorvete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sorvete'),
        ),
    ]
